Add adaptive for complexes page
3s777/yard-frontend pull request #10
Opened 2017-07-22 14:27 UTC by 3s777

https://build-hzocljiebi.now.sh

2017-07-22 17:53 UTC, evgenyrodionov commented
Что-то не то случилось

![image](https://user-images.githubusercontent.com/775692/28493427-c879dcbe-6f1f-11e7-8467-48232bd93223.png)

2017-07-22 17:55 UTC, imevro requested changes
Используй хелперы, чтобы делать ```${media.desktop`padding-top...` }``` не пиши каждый раз `@media (min-width)...`

https://www.styled-components.com/docs/api#helpers

2017-07-22 17:55 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +      padding-left: 0;
чё с табами

2017-07-23 10:00 UTC, 3s777 commented
https://build-unvuahujyx.now.sh/

2017-07-24 11:22 UTC, evgenyrodionov commented
Тоже раздели на два ПРа, зачем весь адаптив в одном делать

2017-07-24 11:22 UTC, evgenyrodionov commented
Список норм работает

2017-07-24 22:41 UTC, imevro approved these changes

2017-07-28 10:01 UTC, merged