Add adaptive complex page
3s777/yard-frontend pull request #11
Opened 2017-07-24 12:55 UTC by 3s777

https://build-unvuahujyx.now.sh

2017-07-24 22:49 UTC, evgenyrodionov commented
А чё заголовок уехал?

![image](https://user-images.githubusercontent.com/775692/28548223-70b2a386-70db-11e7-8abf-24eadc35526c.png)

А тут не должен быть по центру

![image](https://user-images.githubusercontent.com/775692/28548232-7cea447e-70db-11e7-97db-3559f112239a.png)

Тут почему до сих пор статичной картинкой, а не мапбоксом? Плюс что-то с паддингами у времени до места

![image](https://user-images.githubusercontent.com/775692/28548237-89747250-70db-11e7-905f-76b1aed9c138.png)

2017-07-25 16:50 UTC, 3s777 commented
https://build-sammatveec.now.sh/

2017-07-25 20:36 UTC, evgenyrodionov commented
Воткни тестовое описание из макета, сделай кнопку

2017-07-26 08:00 UTC, 3s777 commented
https://build-qfvdnfsgvi.now.sh/

2017-07-27 07:16 UTC, 3s777 commented
https://build-uaxjllnqwo.now.sh/
билд с подключенным api.jqestate.ru/v1/complexes

2017-07-27 11:26 UTC, evgenyrodionov commented
С сеткой что-то не то

![image](https://user-images.githubusercontent.com/775692/28668230-8e003d2e-72d7-11e7-893b-b03fa44384f2.png)

2017-07-27 11:26 UTC, evgenyrodionov commented
И вот тут бы поправить, а то некрасиво
![image](https://user-images.githubusercontent.com/775692/28668243-9bd4c3b6-72d7-11e7-8f61-d60704146388.png)

2017-07-27 11:29 UTC, imevro requested changes

2017-07-27 11:29 UTC, evgenyrodionov commented on .env
> +REACT_APP_MAPBOX_TOKEN=pk.eyJ1IjoianVzdHVzZWJyYWluIiwiYSI6ImNpbHV1dWlmYTAwNmp2Zm02NjZkZmIybGkifQ.feSAgXjbU00mlAjBQyv1lQ
нельзя коммитить в репозиторий конфиденциальные данные!

2017-07-27 11:29 UTC, evgenyrodionov commented on .env
> +REACT_APP_MAPBOX_TOKEN=pk.eyJ1IjoianVzdHVzZWJyYWluIiwiYSI6ImNpbHV1dWlmYTAwNmp2Zm02NjZkZmIybGkifQ.feSAgXjbU00mlAjBQyv1lQ
засунь файл в гитигнор и удали из репозитория

2017-07-27 11:29 UTC, evgenyrodionov commented on src/Complexes/Show/Description.jsx
> +const Readmore = styled.div`
Readmore что?

2017-07-27 11:29 UTC, evgenyrodionov commented on src/Complexes/Show/Description.jsx
> +    const blockHeight = {
это стиль, скорее, не находишь?

2017-07-27 11:29 UTC, evgenyrodionov commented on src/Footer.jsx
> +import { media } from './Complexes/functions';
если ты в футере лезешь в комплексес, ты уверен, что оно должно быть в комплексес?

2017-07-27 11:29 UTC, evgenyrodionov commented on src/Footer.jsx
> +import { media } from './Complexes/functions';
И functions это плохое название, обычно делают директорию `utils`

2017-07-27 11:29 UTC, evgenyrodionov commented on src/Footer.jsx
> +import { media } from './Complexes/functions';
или файл `utils.js`

2017-07-27 17:49 UTC, 3s777 commented
https://build-epacsxyipe.now.sh

2017-07-27 17:53 UTC, imevro requested changes

2017-07-27 17:53 UTC, evgenyrodionov commented on src/utils.jsx
> +import { kinds } from './Translation';
1) эти кайнды относятся только к ЖК, шаришь?
2) почему файл назван как компонент

2017-07-28 08:20 UTC, 3s777 commented
https://build-tptdhoapau.now.sh

2017-07-28 10:00 UTC, evgenyrodionov commented
Нравится

2017-07-28 10:00 UTC, imevro approved these changes

2017-07-28 10:01 UTC, merged