Add data to app
3s777/yard-frontend pull request #7
Opened 2017-07-14 16:41 UTC by 3s777

https://build-evyakddnvi.now.sh/

2017-07-14 17:14 UTC, evgenyrodionov commented
- актуальных описаний нет
- инфраструктура это amenities в апи
- кнопка кол-ва фотографий пропала

2017-07-14 20:24 UTC, 3s777 commented
https://build-gmjqnysxxi.now.sh/

2017-07-14 23:36 UTC, evgenyrodionov commented
Чё с полосами

![image](https://user-images.githubusercontent.com/775692/28234261-5a0a6452-6906-11e7-88c0-ec7fc187fb77.png)

2017-07-14 23:40 UTC, imevro requested changes

2017-07-14 23:40 UTC, evgenyrodionov commented on src/App.jsx
> +      <Route path="/complexes/:id" component={Complex} />
ты же слаг используешь, не айди

2017-07-14 23:40 UTC, evgenyrodionov commented on src/Complexes/List/index.jsx
> +            title={complex.name}
чё-то дохуя параметров передаешь, лучше разбирай их внутри карточки

2017-07-14 23:40 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +            alt="Gallery"
плохой альт

2017-07-14 23:40 UTC, evgenyrodionov commented on src/Complexes/Show/Header.jsx
> +          Район {props.district}, {props.street}, дом {props.house}
а где индекс-то

2017-07-14 23:40 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    function statusCheck(statusData) {
такие функции не нужно в рендере держать, потому что они никакого отношения к компоненту не имеют, их можно вызвать откуда угодно. вынеси за пределы компонента

2017-07-14 23:40 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +            totalArea={{ min: isUndef(tAreaFrom), max: isUndef(tAreaTo) }}
опять же, разбирай это внутри, а не передавай 10 тысяч пропов

2017-07-14 23:40 UTC, evgenyrodionov commented
А также прочти https://github.com/apolyntsev/yard-frontend/pull/8#pullrequestreview-50171527

2017-07-15 10:40 UTC, 3s777 commented
https://build-zdxmwgihxr.now.sh/

2017-07-15 13:21 UTC, imevro requested changes

2017-07-15 13:21 UTC, evgenyrodionov commented on src/getApi.jsx
> +export const imagesUrl = 'https://yard-images.s3.amazonaws.com/';
это к апи никак не относится

2017-07-15 13:21 UTC, evgenyrodionov commented on src/getApi.jsx
> +export function getApi(apiUrl) {
зачем у файла название `getApi`? и у функции тоже

для POST-запросов отдельный файл будет или что?

2017-07-15 13:21 UTC, evgenyrodionov commented on src/getApi.jsx
> +export function getApi(apiUrl) {
пересмотри видео про http

2017-07-15 16:54 UTC, 3s777 commented
https://build-ikwwmyqyzw.now.sh/

2017-07-15 17:44 UTC, imevro requested changes

2017-07-15 17:44 UTC, evgenyrodionov commented on src/Complexes/functions.jsx
> +  return 'Квартира';
вот не надо этого. Если не указано, то лучше не отображать, иначе ты введешь покупателя в заблуждение. Это пиздец какой косяк может быть для бизнеса.

У тебя будет что в ЖК продаются Квартира, а на деле там апартаменты, человек поедет на сделку и просто пиздец как ты навредишь, потому что в апартаментах сложно прописаться http://www.metrinfo.ru/novostroyki/articles/5-voprosov-ob-apartamentah-o-propiske-nalogah.117466.html

2017-07-15 17:44 UTC, evgenyrodionov commented on src/Complexes/functions.jsx
> +export function isUndef(dataToFixed) {
странное название функции

2017-07-15 17:44 UTC, evgenyrodionov commented on src/Complexes/functions.jsx
> +  return null;
можно не писать return, по-умолчанию он вернет undefined если не задать

2017-07-15 17:44 UTC, evgenyrodionov commented on src/api.jsx
> +/* eslint-disable import/prefer-default-export */
Поставь TODO и укажи что нужно убрать это правило когда-нибудь. TODO хорошая тема

2017-07-15 20:37 UTC, 3s777 commented
https://build-njhjfrnyyp.now.sh/
"можно не писать return" я не фиксил, т.к из-за ошибки Expected to return a value at the end of function (consestent-return) ты написал оставить как есть

2017-07-15 21:07 UTC, imevro requested changes

2017-07-15 21:07 UTC, evgenyrodionov commented on src/Complexes/Show/Specifications.jsx
> +            {propertyKind ? <Label>Статус</Label> : null}
conditional rendering через  && лучше тернарника

2017-07-15 21:07 UTC, evgenyrodionov commented on src/api.jsx
> +/* TODO убрать правило когда будут новые методы*/
комментарии всегда на английском

2017-07-15 21:15 UTC, 3s777 commented
https://build-rmkpibjtwx.now.sh/

2017-07-15 21:20 UTC, imevro approved these changes

2017-07-15 21:21 UTC, merged